// Mocks generated by Mockito 5.3.2 from annotations
// in ditonton/test/presentation/pages/tv_show_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:ditonton/common/state_enum.dart' as _i4;
import 'package:ditonton/domain/entities/tv_show_detail.dart' as _i2;
import 'package:ditonton/presentation/provider/tv_show_detail_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import '../../../modules/core/lib/domain/entities/watchlist.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvShowDetail_0 extends _i1.SmartFake implements _i2.TvShowDetail {
  _FakeTvShowDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvShowDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowDetailNotifier extends _i1.Mock
    implements _i3.TvShowDetailNotifier {
  MockTvShowDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowDetail get detail => (super.noSuchMethod(
        Invocation.getter(#detail),
        returnValue: _FakeTvShowDetail_0(
          this,
          Invocation.getter(#detail),
        ),
      ) as _i2.TvShowDetail);
  @override
  _i4.RequestState get detailState => (super.noSuchMethod(
        Invocation.getter(#detailState),
        returnValue: _i4.RequestState.Empty,
      ) as _i4.RequestState);
  @override
  List<_i5.Watchlist> get recommendations => (super.noSuchMethod(
        Invocation.getter(#recommendations),
        returnValue: <_i5.Watchlist>[],
      ) as List<_i5.Watchlist>);
  @override
  _i4.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i4.RequestState.Empty,
      ) as _i4.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  void setId(int? id) => super.noSuchMethod(
        Invocation.method(
          #setId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<void> fetchDetail() => (super.noSuchMethod(
        Invocation.method(
          #fetchDetail,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<String> toggleWatchlist() => (super.noSuchMethod(
        Invocation.method(
          #toggleWatchlist,
          [],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<void> addWatchlist(_i2.TvShowDetail? tvShowDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvShowDetail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> removeFromWatchlist(_i2.TvShowDetail? tvShowDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvShowDetail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> loadWatchlistStatus([int? id]) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
